language: groovy
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_script: unset GEM_PATH GEM_HOME JRUBY_OPTS
install: ./gradlew assemble
script: ./gradlew -S clean build
notifications:
  email: false
